### ISSUE TITLE
Adding multiple twoway graphs to colorscatter

### ISSUE THREAD

**Issue by tabareCapitan** [simonheb/colorscatter#1]
The `tw_pre` and `tw_post` are defined as (lines 45 and 63 in the ado file): 

```
local command tw (`tw_pre')
local command tw (`tw_pre')
``` 
which means that it is not possible to add multiple twoway graphs such as:

`(scatteri 0.1 0.9)  (scatteri 0.4 0.9)`

By removing the two parenthesis from the first two lines of code in this issue, one can now use the line above (or similar) to add 2 twoway graphs to `colorscatter`.  More than 2 graphs are also possible.

Perhaps this might be of use to someone else.

---

Disclaimer: Not really an issue. Just an expansion on a current feature.

**Comment by simonheb** [comment]
Oh thanks for pointing this out. I didn't know anyone besides me was actually using `colorscatter` :)

I made some changes to the code, is this what you had in mind?

**Comment by tabareCapitan** [comment]
Yep, that's exactly what I meant. It's super useful, I'm pretty sure lots of people have used it.
